"""empty message

Revision ID: 45ebeab4c158
Revises: 
Create Date: 2023-11-03 07:06:59.738723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45ebeab4c158'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('cust_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cust_name', sa.String(length=50), nullable=False),
    sa.Column('cust_address', sa.String(length=50), nullable=False),
    sa.Column('cust_city', sa.String(length=30), nullable=False),
    sa.Column('cust_state', sa.String(length=20), nullable=False),
    sa.Column('cust_zip', sa.String(length=7), nullable=False),
    sa.Column('cust_country', sa.String(length=25), nullable=False),
    sa.Column('cust_telp', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('cust_id')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('judul', sa.VARCHAR(length=50), nullable=False),
    sa.Column('pathname', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=False)

    op.create_table('orders',
    sa.Column('order_num', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('cust_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cust_id'], ['customers.cust_id'], ),
    sa.PrimaryKeyConstraint('order_num')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('images')
    op.drop_table('customers')
    # ### end Alembic commands ###
